name : CI

on:
  workflow_dispatch:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  validate-notebooks-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: 3.11.14
           
      - name: Install Qiskit and notebook tools
        run: 
          pip install qiskit==2.2.3 nbconvert nbformat matplotlib pandas ipykernel
       
      - name: Install Jupyter kernel
        
        run: |
          python -m ipykernel install --user --name python3 --display-name "Python 3"


      - name: Run Jupyter notebooks
        run: |
         
          NOTEBOOKS=$(find . -name "*.ipynb")
          for nb in $NOTEBOOKS ; do
            echo "Running $nb ..."
            jupyter nbconvert --to notebook --execute \
              --ExecutePreProcessor.timeout=600 \
              --allow-errors "$nb"
          done
          

        
      
